import { 
  Newspaper, 
  Palmtree, 
  Trophy, 
  HeartPulse, 
  GraduationCap, 
  MessageSquare, 
  FileText, 
  BookOpen, 
  Cpu, 
  Zap, 
  Globe, 
  Camera, 
  Music, 
  Utensils, 
  Briefcase,
  ShieldCheck
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, any> = {
  'General': Newspaper,
  'Noticias': Newspaper,
  'Cultura': Palmtree,
  'Deportes': Trophy,
  'Salud': HeartPulse,
  'Educación': GraduationCap,
  'Opinión': MessageSquare,
  'Reportajes': FileText,
  'Revista': BookOpen,
  'Tecnología': Cpu,
  'Entretenimiento': Zap,
  'Mundo': Globe,
  'Fotografía': Camera,
  'Música': Music,
  'Gastronomía': Utensils,
  'Negocios': Briefcase,
  'Local': Newspaper,
  'Policiaca': ShieldCheck,
  'Clima': Zap,
};

export const DEFAULT_CATEGORIES = [
  'General',
  'Noticias',
  'Cultura',
  'Deportes',
  'Salud',
  'Educación',
  'Opinión',
  'Reportajes',
  'Revista',
  'Tecnología',
  'Entretenimiento',
  'Mundo',
  'Fotografía',
  'Música',
  'Gastronomía',
  'Negocios'
];
